apiVersion: apps/v1
kind: Deployment
metadata:
  name: sojourn-backend
spec:
  selector:
    matchLabels:
      app: sojourn-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: sojourn-backend
    spec:
      containers:
      - name: nginx
        image: sukreshmanda/sojourn:latest
        env:
          - name: MONGO_HOST
            value: ${MONGO_HOST}
          - name: MONGO_PORT
            value: ${MONGO_PORT}
        ports:
        - containerPort: 1234

---
apiVersion: v1
kind: Service
metadata:
  name: backend-cluster-service
spec:
  type: ClusterIP
  selector:
    app: sojourn-backend
  ports:
  - name: http
    port: 1234
    targetPort: 1234
